# NumPy Array Attributes

In [3]:
import numpy as np
#np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [6]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

print("x3 type:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 type: int64
itemsize: 8 bytes
nbytes: 480 bytes


# Array Indexing: Accessing Single Elements¶

In [10]:
x1

array([4, 3, 4, 4, 8, 4])

In [11]:
x1[4]

8

In [14]:
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [15]:
x2[2,3]

0

Values can also be modified using any of the above index notation:

In [16]:
x2[0,0]=12
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [17]:
x3[0,0,0]=7.8 # be truncated to 7
x3

array([[[7, 2, 4, 2, 0],
        [3, 2, 0, 7, 5],
        [9, 0, 2, 7, 2],
        [9, 2, 3, 3, 2]],

       [[3, 4, 1, 2, 9],
        [1, 4, 6, 8, 2],
        [3, 0, 0, 6, 0],
        [6, 3, 3, 8, 8]],

       [[8, 2, 3, 2, 0],
        [8, 8, 3, 8, 2],
        [8, 4, 3, 0, 4],
        [3, 6, 9, 8, 0]]])

# Array Slicing: Accessing Subarrays
x[start:stop:step]

they default to the values start=0, stop=size of dimension, step=1

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [19]:
x=np.arange(10)
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [21]:
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [22]:
x2[:2,:3] #two rows three columns

array([[12,  7,  5],
       [ 0,  1,  5]])

In [24]:
x2[::,::2] # all rows, every other column

array([[12,  5],
       [ 0,  5],
       [ 3,  5]])

In [32]:
# first column of x2
print(x2[:,0])
# first row of x2
print(x2[0,:])
#or
print(x2[0])

[12  0  3]
[12  7  5  5]
[12  7  5  5]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [33]:
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [43]:
sub_x2=x2[:2,:2]
print(sub_x2)

[[12  7]
 [ 0  1]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [44]:
sub_x2[0,0]=99
print(sub_x2)

[[99  7]
 [ 0  1]]


In [45]:
print(x2)

[[99  7  5  5]
 [ 0  1  5  9]
 [ 3  0  5  0]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [48]:
sub1=x2[:2,:2].copy()
print(sub1)

[[99  7]
 [ 0  1]]


In [49]:
sub1[0,0]=33
print(sub1)
print(x2)

[[33  7]
 [ 0  1]]
[[99  7  5  5]
 [ 0  1  5  9]
 [ 3  0  5  0]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [52]:
g=np.arange(1,16).reshape((3,5))
print(g)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [64]:
x=np.array([1,2,3,4,5,6])
x.reshape((2,3))


array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
x[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6]])

In [66]:
x.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
x[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

# Concatenation of arrays¶

In [69]:
x=np.array([1,2,3])
y=np.array([4,6,7])
np.concatenate([x,y])

array([1, 2, 3, 4, 6, 7])

In [70]:
z=np.array([10,20,30])
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  6,  7, 10, 20, 30])

In [71]:
grid = np.array([[1, 2, 3],[4, 5, 6]])

In [72]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

##### For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [76]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
# vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [79]:
# horizontally stack the arrays
x=np.array([[10],[20]])
np.hstack([x,grid])

array([[10,  9,  8,  7],
       [20,  6,  5,  4]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [83]:
x=np.array([1,2,3,4,5,6,7,8,9])
x1,x2,x3=np.split(x,[3,7]) #3,7 are splitting index
print(x1,x2,x3)

[1 2 3] [4 5 6 7] [8 9]


In [87]:
grid = np.arange(16).reshape((4, 4))
a,b=np.vsplit(grid,[3])
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [89]:
c,d=np.hsplit(grid,[1])
print(c)
print(d)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
