The advantage of the list is flexibility;
NumPy lack flexibility but is efficient for storing and manipulating data

# Fixed-type array
 The built-in array module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [9]:
import array
l=list(range(30))

a=array.array('f',l) #f means type of list is float

#a=array.array(l)
a


array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0])

# Creating Arrays from Python Lists¶


In [ ]:
import numpy as np
np.array([1,2,3,4,5])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [11]:
np.array([2.34,5,6,8.0,9.3])

array([ 2.34,  5.  ,  6.  ,  8.  ,  9.3 ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [17]:
np.array([2.34,5,6,8.0,9.3],dtype='int')

array([2, 5, 6, 8, 9])

NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [23]:
# nested lists result in multi-dimensional arrays
np.array([range(i,i+3) for i in [3,9,22]])

array([[  2,   4,   8],
       [  4,  16,  64],
       [  6,  36, 216]])

In [24]:
np.array([[i,pow(i,2),pow(i,3)] for i in [2, 4, 6]])

array([[  2,   4,   8],
       [  4,  16,  64],
       [  6,  36, 216]])

# Creating Arrays from Scratch

In [25]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones((2,4),dtype='float')

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [27]:
# Create a 3x6 array filled with 3
np.full((3,6),3)

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [28]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
# Create an array of five values evenly spaced between 0 and 10
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [30]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.21547438, -2.12389127, -1.60967407],
       [-0.39477287,  0.30936745,  0.51464522],
       [ 2.28298421,  1.54286053,  0.79821779]])

In [31]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(2,5))

array([[4, 4, 9, 5, 4],
       [7, 9, 7, 8, 1]])

In [34]:
# Create a 6x6 identity matrix
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [36]:
np.empty((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])